package com.jdmc.constants;

public enum Actions {
    PRIVILEGED_GET_AUTOMOBILES,
    REGISTER_MORE_INFO,
    CLOSE_CONNECTION,
    GET_AUTOMOBILES,
    GET_USER_ORDERS,
    MAKE_BUY_ORDER,
    DECLINE_ORDER,
    REMOVE_ORDER,
    DELETE_USER,
    APPLY_ORDER,
    GET_ORDERS,
    DELETE_CAR,
    ADD_ENTRY,
    GET_USERS,
    EDIT_USER,
    AUTHORIZE,
    REGISTER,
    EDIT_CAR,
    ADD_USER
}
